# Generated by Django 5.1.4 on 2024-12-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
